const ReportActions = {
    GET_GENERAL_OPTIONS: 'GET_GENERAL_OPTIONS',
    GET_COUNTRY_OPTIONS: 'GET_COUNTRY_OPTIONS',
    GET_COUNTRY_FILTERS: 'GET_COUNTRY_FILTERS',
    GET_GENERAL_REPORT: 'GET_GENERAL_REPORT',
    SET_REPORT_TYPE: 'SET_REPORT_TYPE',
    GET_COUNTRY_REPORT: 'GET_COUNTRY_REPORT',
};

export default ReportActions;
